pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:codescope1/split-smart.git
          - cd split-smart.git
          - git push --mirror git@github.com:ParP924/split-smart.git